# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 935bc9cab9b608b99324855ca85cf600d718351b029414e5eaa0614cb7988a8c3dccbc4c62d5cdafa26471b8dde685ba9f9b7a106483bce64b42475b790c94b3

test:
  secret_key_base: ad1f370a826812a52b35b616ef00153dd68a7ab3606bcbfdba29fadedbeacd2f8c29100802ee7b72a6816ae87044e94598aa9633c303bb365216582723bf0eca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
